apiVersion: apps/v1
kind: Deployment
metadata:
  name: khushi-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: khushi-app
  template:
    metadata:
      labels:
        app: khushi-app
    spec:
      containers:
      - name: khushi-app
        image: pb26uk/khushi:latest  # Use your Docker image here
        ports:
        - containerPort: 80  # Exposing port 80, since your app runs on port 80
        env:
        - name: PORT
          value: "80"  # Set the environment variable if needed
