apiVersion: apps/v1
kind: Deployment
metadata:
  name: khushi-app
  labels:
    app: khushi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: khushi-app
  template:
    metadata:
      labels:
        app: khushi-app
    spec:
      containers:
      - name: khushi-container
        image: pb26uk/khushi
        ports:
        - containerPort: 3000
